apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-backend
  namespace: soludev
spec:
  provider:
    vault:
      server: "http://openbao.soludev.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes/"
          role: "external-secrets-role"
          serviceAccountRef:
            name: "external-secrets-sa"
            namespace: "soludev"