apiVersion: apps/v1
kind: Deployment
metadata:
  name: prospectio-landing
  namespace: prospectio
  labels:
    app: prospectio-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prospectio-landing
  template:
    metadata:
      labels:
        app: prospectio-landing
    spec:
      tolerations:
        - key: "klipperlb-exclude"
          value: "true"
          effect: "NoSchedule"
          operator: "Equal"
      containers:
        - name: prospectio-landing
          image: kaiohz/prospectio-landing:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
