server:
  # Utiliser le service account avec permissions TokenReview
  serviceAccount:
    create: false
    name: openbao
  tolerations:
    - key: klipperlb-exclude
      value: "true"
      effect: NoSchedule
      operator: Equal
  nodeSelector:
    type: standard