apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    # Garder les ports existants + ajouter le port vault
    ports:
      web:
        port: 8080
        expose: true
        exposedPort: 80
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
        tls:
          enabled: true
      vault:
        port: 8200
        expose: true
        exposedPort: 8200