apiVersion: apps/v1
kind: Deployment
metadata:
  name: prospectio-front
  labels:
    app: prospectio-front
spec:
  nodeSelector:
    light: "true"
  replicas: 1
  selector:
    matchLabels:
      app: prospectio-front
  template:
    metadata:
      labels:
        app: prospectio-front
    spec:
      initContainers:
      - name: env-replacer
        image: busybox
        command: ['sh', '-c', 'envsubst < /app/index.html > /shared/index.html && cp -r /app/* /shared/']
        env:
        - name: VITE_APP_RAG_CHATBOT_API_URL
          valueFrom:
            configMapKeyRef:
              name: prospectio-front-config
              key: VITE_APP_RAG_CHATBOT_API_URL
        - name: VITE_APP_BACKEND_API_URL
          valueFrom:
            configMapKeyRef:
              name: prospectio-front-config
              key: VITE_APP_BACKEND_API_URL
      tolerations:
        - key: "klipperlb-exclude"
          value: "true"
          effect: "NoSchedule"
          operator: "Equal"
      containers:
        - name: prospectio-front
          image: kaiohz/prospectio-front:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: prospectio-front-config
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
