# cloudflared-deployment-fixed.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: kaiohz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      # Configuration DNS avec serveurs externes
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - "1.1.1.1"
        - "8.8.8.8"
        searches:
        - kaiohz.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        options:
        - name: ndots
          value: "5"
      
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config.yml
        - run
        - --token
        - $(TUNNEL_TOKEN)
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: token
        # Forcer l'utilisation de DNS externes
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      
      volumes:
      - name: config
        configMap:
          name: cloudflared-config
      
      restartPolicy: Always