apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
  namespace: kaiohz
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: cloudflare
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: prospectio/cloudflare