apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector
  labels:
    app: pgvector
spec:
  nodeSelector:
    light: "true"  
  replicas: 1
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      tolerations:
        - key: "klipperlb-exclude"
          value: "true"
          effect: "NoSchedule"
          operator: "Equal"
      containers:
        - name: pgvector
          image: pgvector/pgvector:0.8.0-pg17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "prospectio"
            - name: POSTGRES_PASSWORD
              value: "prospectio"
            - name: POSTGRES_DB
              value: "prospectio"
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "prospectio", "-d", "prospectio"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: init-sql
          configMap:
            name: pgvector-init