apiVersion: apps/v1
kind: Deployment
metadata:
  name: prospectio-api-mcp
  labels:
    app: prospectio-api-mcp
spec:
  nodeSelector:
    light: "true"
  replicas: 1
  selector:
    matchLabels:
      app: prospectio-api-mcp
  template:
    metadata:
      labels:
        app: prospectio-api-mcp
    spec:
      tolerations:
        - key: "klipperlb-exclude"
          value: "true"
          effect: "NoSchedule"
          operator: "Equal"
      containers:
        - name: prospectio-api-mcp
          image: kaiohz/prospectio-api-mcp:latest
          ports:
            - containerPort: 7002
          envFrom:
            - configMapRef:
                name: prospectio-api-mcp-config
            - secretRef:
                name: prospectio-api-mcp-secret
          livenessProbe:
            httpGet:
              path: /docs
              port: 7002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /docs
              port: 7002
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "2048Mi"
              cpu: "1500m"
