apiVersion: v1
kind: ConfigMap
metadata:
  name: logto-config
  namespace: soludev
data:
  TRUST_PROXY_HEADER: "1"
  ENDPOINT: "https://dev-logto.soludev.tech/api"
  ADMIN_ENDPOINT: "https://dev-logto.soludev.tech/admin"
  NODE_ENV: "test"